name: backend ci flow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    # paths:
    #   - 'starter/backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip3 install --upgrade pipenv
        working-directory: starter/backend
      - run: pipenv install
        working-directory: starter/backend
      - run: pipenv run test
        working-directory: starter/backend
