name: frontend ci flow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building"
      - run: echo "Hello"